### ISSUE TITLE
Error with date field

### ISSUE THREAD

**Issue by edalzell** [doublethreedigital/runway#89]
### Description

I have a date field (sql type `date`) with this in the blueprint:

```yaml
        handle: birthdate
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: Birthdate
          type: date
          icon: date
```

When I try to load a model detail page in the CP I get a carbon error: <img width="1264" alt="CleanShot 2021-10-19 at 19 31 43@2x" src="https://user-images.githubusercontent.com/6069653/138018416-067e2024-9c0d-4700-aada-c9eee1317b47.png">

### Steps to reproduce

1. have a date field in the blueprint
2. try to load a model in the CP

### Environment

```
Statamic 3.2.16 Pro
Laravel 8.64.0
PHP 8.0.11
aryehraber/statamic-captcha 1.5.2
aryehraber/statamic-uuid 2.0.3
doublethreedigital/runway 2.1.27
edalzell/download dev-main
edalzell/forma 1.0
jonassiewertsen/statamic-livewire 2.7.0
statamic/seo-pro 2.3.2
transformstudios/events 2.2.2
transformstudios/front 1.7.1
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/memorial dev-feature/orphan-portal
transformstudios/price-of dev-feature/orphan-portal
transformstudios/review 3.1
transformstudios/simple dev-main
transformstudios/stripe dev-main
transformstudios/takeover-redirects dev-main
```
